class ActionTypeEnum:
    LOGIN = "LOGIN"
    LOGOUT = "LOGOUT"
    SIGNUP = "SIGNUP"
    SUBORG = "SUBORG"
    SUBCATEGORY = "SUBCATEGORY"
    UNSUBCATEGORY = "UNSUBCATEGORY"
    SUBKEYWORD = "SUBKEYWORD"
    UNSUBKEYWORD = "UNSUBKEYWORD"
    LIKEFEEDBACK = "LIKEFEEDBACK"
    VIEWCONTENTS = "VIEWCONTENTS"
    REGISTERORG = "REGISTERORG"

class SignMethodEnum:
    NORMAL = "NORMAL"
    KAKAO = "KAKAO"
    NAVER = "NAVER"
    GOOGLE = "GOOGLE"    