from ksubscribe_share.db.dbmodelV2.contentsOrgVO import (
    ContentsOrgVO,
    ContentsOrgCategory,
)
from ksubscribe_share.db.dbmodelV2.commCodeVO import commCodeVO
from ksubscribe_share.db.mongoManager import MongoClient, MongoManager
from ksubscribe_share.db.service.contentsOrgService import ContentsOrgService



inputs = [
    {"org_id":"A0001", "category_id":"B0001", "collectMethod":"onlyPdf","tagElement":"","tagAttr":"","tagAttrValue":"" },                                   
    {"org_id":"A0001", "category_id":"B0002", "collectMethod":"textInTag","tagElement":"article","tagAttr":"id","tagAttrValue":"cont-body" },
    {"org_id":"A0001", "category_id":"B0010", "collectMethod":"textInBody","tagElement":"","tagAttr":"","tagAttrValue":"" },
    {"org_id":"A0001", "category_id":"B0011", "collectMethod":"textInTag","tagElement":"article","tagAttr":"id","tagAttrValue":"cont-body"},
    {"org_id":"A0001", "category_id":"B0012", "collectMethod":"textInTag","tagElement":"article","tagAttr":"id","tagAttrValue":"cont-body"},
    {"org_id":"A0002", "category_id":"B0001", "collectMethod":"textInTag","tagElement":"div","tagAttr":"id","tagAttrValue":"start_contents"},
    {"org_id":"A0002", "category_id":"B0003", "collectMethod":"textInTag","tagElement":"div","tagAttr":"id","tagAttrValue":"start_contents"},
    {"org_id":"A0002", "category_id":"B0010", "collectMethod":"textInBody","tagElement":"","tagAttr":"","tagAttrValue":"" },
    {"org_id":"A0003", "category_id":"B0002", "collectMethod":"textInTag","tagElement":"div","tagAttr":"class","tagAttrValue":"sub_contents"},
    {"org_id":"A0003", "category_id":"B0003", "collectMethod":"textInTag","tagElement":"div","tagAttr":"id","tagAttrValue":"divMainArticle"},
    {"org_id":"A0003", "category_id":"B0010", "collectMethod":"textInBody","tagElement":"","tagAttr":"","tagAttrValue":"" },
    {"org_id":"A0004", "category_id":"B0005", "collectMethod":"","tagElement":"","tagAttr":"","tagAttrValue":""},
    {"org_id":"A0005", "category_id":"B0002", "collectMethod":"textInTag","tagElement":"div","tagAttr":"id","tagAttrValue":"container-sub"},
    {"org_id":"A0005", "category_id":"B0003", "collectMethod":"textInTag","tagElement":"div","tagAttr":"id","tagAttrValue":"container-sub"},
    {"org_id":"A0005", "category_id":"B0005", "collectMethod":"textInTag","tagElement":"div","tagAttr":"id","tagAttrValue":"container-sub"},
    {"org_id":"A0005", "category_id":"B0010", "collectMethod":"textInBody","tagElement":"","tagAttr":"","tagAttrValue":"" },
    {"org_id":"A0006", "category_id":"B0001", "collectMethod":"textInTag","tagElement":"section","tagAttr":"class","tagAttrValue":"lb_con"},
    {"org_id":"A0006", "category_id":"B0003", "collectMethod":"textInTag","tagElement":"section","tagAttr":"class","tagAttrValue":"lb_con"},
    {"org_id":"A0006", "category_id":"B0005", "collectMethod":"textInTag","tagElement":"section","tagAttr":"class","tagAttrValue":"lb_con"},
    {"org_id":"A0006", "category_id":"B0010", "collectMethod":"textInBody","tagElement":"","tagAttr":"","tagAttrValue":"" },
    {"org_id":"A0007", "category_id":"B0002", "collectMethod":"textInTag","tagElement":"section","tagAttr":"id","tagAttrValue":"content"},
    {"org_id":"A0007", "category_id":"B0010", "collectMethod":"textInBody","tagElement":"","tagAttr":"","tagAttrValue":"" },
    {"org_id":"A0008", "category_id":"B0003", "collectMethod":"textInTag","tagElement":"section","tagAttr":"id","tagAttrValue":"sub_contentsArea"},
    {"org_id":"A0008", "category_id":"B0005", "collectMethod":"textInTag","tagElement":"section","tagAttr":"id","tagAttrValue":"sub_contentsArea"},
    {"org_id":"A0008", "category_id":"B0010", "collectMethod":"textInBody","tagElement":"","tagAttr":"","tagAttrValue":"" },
    {"org_id":"A0009", "category_id":"B0002", "collectMethod":"textInTag","tagElement":"div","tagAttr":"id","tagAttrValue":"bbs1view2"},
    {"org_id":"A0009", "category_id":"B0010", "collectMethod":"textInBody","tagElement":"","tagAttr":"","tagAttrValue":"" },
    {"org_id":"A0010", "category_id":"B0001", "collectMethod":"onlyPDF","tagElement":"","tagAttr":"","tagAttrValue":""},
    {"org_id":"A0010", "category_id":"B0010", "collectMethod":"textInBody","tagElement":"","tagAttr":"","tagAttrValue":"" },
    {"org_id":"A0011", "category_id":"B0001", "collectMethod":"textInTag","tagElement":"article","tagAttr":"","tagAttrValue":""},
    {"org_id":"A0011", "category_id":"B0010", "collectMethod":"textInBody","tagElement":"","tagAttr":"","tagAttrValue":"" },
    {"org_id":"A0012", "category_id":"B0001", "collectMethod":"textInTag","tagElement":"div","tagAttr":"id","tagAttrValue":"container-body"},    
    {"org_id":"A0012", "category_id":"B0010", "collectMethod":"textInBody","tagElement":"","tagAttr":"","tagAttrValue":"" },
    {"org_id":"A0013", "category_id":"B0001", "collectMethod":"textInBody","tagElement":"","tagAttr":"","tagAttrValue":""},
    {"org_id":"A0013", "category_id":"B0010", "collectMethod":"textInBody","tagElement":"","tagAttr":"","tagAttrValue":"" },
    {"org_id":"A0014", "category_id":"B0001", "collectMethod":"textInTag","tagElement":"section","tagAttr":"id","tagAttrValue":"subContent"},
    {"org_id":"A0014", "category_id":"B0010", "collectMethod":"textInBody","tagElement":"","tagAttr":"","tagAttrValue":"" },
    {"org_id":"A0015", "category_id":"B0001", "collectMethod":"textInTag","tagElement":"table","tagAttr":"class","tagAttrValue":"tableV"},
    {"org_id":"A0015", "category_id":"B0010", "collectMethod":"textInBody","tagElement":"","tagAttr":"","tagAttrValue":"" },
    {"org_id":"A0016", "category_id":"B0001", "collectMethod":"textInTag","tagElement":"div","tagAttr":"id","tagAttrValue":"wrapContent"},
    {"org_id":"A0016", "category_id":"B0010", "collectMethod":"textInBody","tagElement":"","tagAttr":"","tagAttrValue":"" },
    {"org_id":"A0017", "category_id":"B0001", "collectMethod":"textInTag","tagElement":"div","tagAttr":"class","tagAttrValue":"wrap"},
    {"org_id":"A0017", "category_id":"B0010", "collectMethod":"textInBody","tagElement":"","tagAttr":"","tagAttrValue":"" },
    {"org_id":"A0018", "category_id":"B0001", "collectMethod":"textInTag","tagElement":"div","tagAttr":"class","tagAttrValue":"scSec_cont bb_n"},
    {"org_id":"A0018", "category_id":"B0010", "collectMethod":"textInBody","tagElement":"","tagAttr":"","tagAttrValue":"" },
    {"org_id":"A0019", "category_id":"B0001", "collectMethod":"textInTag","tagElement":"section","tagAttr":"id","tagAttrValue":"content_in"},
    {"org_id":"A0019", "category_id":"B0010", "collectMethod":"textInBody","tagElement":"","tagAttr":"","tagAttrValue":"" },
    {"org_id":"A0020", "category_id":"B0001", "collectMethod":"textInTag","tagElement":"div","tagAttr":"id","tagAttrValue":"right_column"},
    {"org_id":"A0020", "category_id":"B0010", "collectMethod":"textInBody","tagElement":"","tagAttr":"","tagAttrValue":"" },
    {"org_id":"A0021", "category_id":"B0001", "collectMethod":"textInTag","tagElement":"section","tagAttr":"id","tagAttrValue":"content"},
    {"org_id":"A0021", "category_id":"B0010", "collectMethod":"textInBody","tagElement":"","tagAttr":"","tagAttrValue":"" },
    {"org_id":"A0022", "category_id":"B0003", "collectMethod":"textInTag","tagElement":"div","tagAttr":"id","tagAttrValue":"content"},
    {"org_id":"A0022", "category_id":"B0010", "collectMethod":"textInBody","tagElement":"","tagAttr":"","tagAttrValue":"" },
    {"org_id":"A0022", "category_id":"B0004", "collectMethod":"textInTag","tagElement":"div","tagAttr":"id","tagAttrValue":"content"},
    {"org_id":"A0023", "category_id":"B0003", "collectMethod":"textInTag","tagElement":"div","tagAttr":"class","tagAttrValue":"board_wrap"},
    {"org_id":"A0023", "category_id":"B0004", "collectMethod":"textInTag","tagElement":"div","tagAttr":"class","tagAttrValue":"board_wrap"},
    {"org_id":"A0023", "category_id":"B0010", "collectMethod":"textInBody","tagElement":"","tagAttr":"","tagAttrValue":"" },
    {"org_id":"A0024", "category_id":"B0006", "collectMethod":"textInTag","tagElement":"div","tagAttr":"class","tagAttrValue":"notice_view"},
    {"org_id":"A0024", "category_id":"B0010", "collectMethod":"textInBody","tagElement":"","tagAttr":"","tagAttrValue":"" },
    {"org_id":"A0025", "category_id":"B0003", "collectMethod":"textInTag","tagElement":"div","tagAttr":"class","tagAttrValue":"cont"},
    {"org_id":"A0025", "category_id":"B0010", "collectMethod":"textInBody","tagElement":"","tagAttr":"","tagAttrValue":"" },
    {"org_id":"A0026", "category_id":"B0010", "collectMethod":"textInBody","tagElement":"","tagAttr":"","tagAttrValue":"" },
    {"org_id":"A0027", "category_id":"B0001", "collectMethod":"textInTag","tagElement":"div","tagAttr":"class","tagAttrValue":"content_sub_content"},
    {"org_id":"A0027", "category_id":"B0010", "collectMethod":"textInBody","tagElement":"","tagAttr":"","tagAttrValue":"" },
    {"org_id":"A0027", "category_id":"B0003", "collectMethod":"textInTag","tagElement":"div","tagAttr":"class","tagAttrValue":"content_sub_content"},
    {"org_id":"A0028", "category_id":"B0001", "collectMethod":"textInTag","tagElement":"div","tagAttr":"id","tagAttrValue":"contents_start"},
    {"org_id":"A0028", "category_id":"B0002", "collectMethod":"textInTag","tagElement":"div","tagAttr":"id","tagAttrValue":"contents_start"},
    {"org_id":"A0028", "category_id":"B0005", "collectMethod":"textInTag","tagElement":"article","tagAttr":"id","tagAttrValue":"cont-body"},
    {"org_id":"A0028", "category_id":"B0010", "collectMethod":"textInBody","tagElement":"","tagAttr":"","tagAttrValue":"" },
    {"org_id":"A0029", "category_id":"B0001", "collectMethod":"onlyPDF","tagElement":"","tagAttr":"","tagAttrValue":""},
    {"org_id":"A0029", "category_id":"B0005", "collectMethod":"onlyPDF","tagElement":"","tagAttr":"","tagAttrValue":""},
    {"org_id":"A0029", "category_id":"B0003", "collectMethod":"onlyPDF","tagElement":"","tagAttr":"","tagAttrValue":""}    
]

contentsOrgService = ContentsOrgService()

for item in inputs: 
    contentsOrgService.updateCollectInfo(item["org_id"],item["category_id"],item["collectMethod"],item["tagElement"],item["tagAttr"],item["tagAttrValue"])
